# nf-core/genomeannotator basic config file
# More options are documented at: https://nf-co.re/genomeannotator/parameters
# Output directory
outdir: "results"
# Path to your genome assembly
assembly: ""
# Path to proteins from related organisms
proteins: false
# Path to proteins from this organism
proteins_targeted: false
# Path to pre-assembled transcripts/ESTs
transcripts: false
# Path to repeats in FASTA format
rm_lib: false
# Taxonomic group for repeat-masking
rm_species: false
# Path to RNA-seq samplesheet
rnaseq_samples: false
# Path to samplesheet for synteny analysis
references: false
# AUGUSTUS species/model
aug_species: "human"
# AUGUSTUS additional options
aug_options: "--singlestrand=true --alternatives-from-evidence=on --minexonintronprob=0.08 --minmeanexonintronprob=0.4 --maxtracks=3"
# SPALN profile
spaln_taxon: false
# Search for ncRNAs with RFam
ncrna: false
# Reconstruct transcriptome de-novo
trinity: false
# PASA gene build pipeline
pasa: false
# PASA alignment options (minimap2, gmap and/or blat)
pasa_aligner: "minimap2"
# Consensus gene building
evm: false
# Largest possible intron
max_intron_size: 50000
# Remove scaffolds smaller than this
min_contig_size: 5000
